name: "Django Workflow"
on: [push, pull_request]
permissions:
  contents: read
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.13, 3.12]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run Tests
        run: |
          python manage.py test
        env:
          RIDWAANHALL_MAIN_API: ${{ secrets.RIDWAANHALL_MAIN_API }}
          API_KEY: ${{ secrets.API_KEY }}
          RIDWAANHALL_API_X: ${{ secrets.RIDWAANHALL_API_X }}
          RIDWAANHALL_X: ${{ secrets.RIDWAANHALL_X }}
          RIDWAANHALL_HASH_X: ${{ secrets.RIDWAANHALL_HASH_X }}
          RIDWAANHALL_API_KEY: ${{ secrets.RIDWAANHALL_API_KEY }}
          RIDWAANHALL_KEY: ${{ secrets.RIDWAANHALL_KEY }}
          RIDWAANHALL_HASH_KEY: ${{ secrets.RIDWAANHALL_HASH_KEY }}
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
